# Generated by Django 4.2.24 on 2025-10-05 12:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Bodega principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud GPS')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud GPS')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto (máximo 20 caracteres)', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo promedio')),
                ('precio_minorista', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio minorista')),
                ('precio_mayorista', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio mayorista')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock mínimo')),
                ('maneja_variantes', models.BooleanField(default=False, verbose_name='Maneja variantes')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_variante', models.CharField(choices=[('talla', 'Talla'), ('color', 'Color')], max_length=20, verbose_name='Tipo')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor')),
                ('codigo_variante', models.CharField(max_length=50, unique=True, verbose_name='Código variante')),
                ('costo_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo promedio específico')),
                ('precio_minorista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio minorista específico')),
                ('precio_mayorista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio mayorista específico')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de productos',
                'ordering': ['producto__codigo', 'tipo_variante', 'valor'],
                'unique_together': {('producto', 'tipo_variante', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['categoria__nombre', 'nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del proveedor', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre o Razón Social')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT/Cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('contacto_principal', models.CharField(blank=True, max_length=100, verbose_name='Contacto Principal')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Contacto')),
                ('calificacion', models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=5, verbose_name='Calificación (1-5 estrellas)')),
                ('confiable', models.BooleanField(default=True, verbose_name='Proveedor Confiable')),
                ('dias_credito', models.PositiveIntegerField(default=0, verbose_name='Días de Crédito')),
                ('descuento_pronto_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Descuento Pronto Pago')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de Compra')),
                ('precio_compra_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Anterior')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('stock_proveedor', models.PositiveIntegerField(default=0, verbose_name='Stock del Proveedor')),
                ('tiempo_entrega_dias', models.PositiveIntegerField(default=7, verbose_name='Días de Entrega')),
                ('cantidad_minima_pedido', models.PositiveIntegerField(default=1, verbose_name='Cantidad Mínima')),
                ('descuento_volumen', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Descuento por Volumen')),
                ('cantidad_descuento', models.PositiveIntegerField(default=0, verbose_name='Cantidad para Descuento')),
                ('fecha_ultimo_precio', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('proveedor_preferido', models.BooleanField(default=False, verbose_name='Proveedor Preferido')),
                ('activo', models.BooleanField(default=True, verbose_name='Relación Activa')),
                ('notas', models.TextField(blank=True, verbose_name='Notas y Observaciones')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_proveedores', to='inventario.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_productos', to='inventario.proveedor')),
                ('usuario_actualizo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto-Proveedor',
                'verbose_name_plural': 'Productos-Proveedores',
                'ordering': ['proveedor_preferido', 'precio_compra'],
                'unique_together': {('producto', 'proveedor')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.subcategoria', verbose_name='Subcategoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrdenCompraStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True, verbose_name='Entrega Esperada')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada al Proveedor'), ('confirmada', 'Confirmada'), ('parcial', 'Recibida Parcial'), ('completa', 'Recibida Completa'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal')),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Descuento Total')),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('generada_por_alerta', models.BooleanField(default=False, verbose_name='Generada por Alerta de Stock')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='inventario.proveedor', verbose_name='Proveedor')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia')], max_length=20)),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('reserva', 'Reserva para venta'), ('liberacion_reserva', 'Liberación de reserva'), ('devolucion_cliente', 'Devolución cliente'), ('devolucion_proveedor', 'Devolución proveedor'), ('ajuste_inventario', 'Ajuste inventario'), ('transferencia', 'Transferencia entre bodegas'), ('producto_dañado', 'Producto dañado'), ('producto_vencido', 'Producto vencido')], max_length=30)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo unitario')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, verbose_name='Documento referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('pedido_referencia', models.UUIDField(blank=True, null=True, verbose_name='ID Pedido referencia')),
                ('factura_referencia', models.UUIDField(blank=True, null=True, verbose_name='ID Factura referencia')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega')),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_recibidos', to='inventario.bodega', verbose_name='Bodega destino')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('cantidad_reservada', models.IntegerField(default=0, verbose_name='Cantidad reservada')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventario.producto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['bodega__nombre', 'producto__codigo'],
                'unique_together': {('producto', 'variante', 'bodega')},
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenCompraStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Unitario')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Descuento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.ordencomprastock')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
                ('producto_proveedor', models.ForeignKey(help_text='Relación específica producto-proveedor de donde se tomaron precio y condiciones', on_delete=django.db.models.deletion.CASCADE, to='inventario.productoproveedor', verbose_name='Producto-Proveedor')),
            ],
            options={
                'verbose_name': 'Item de Orden de Compra',
                'verbose_name_plural': 'Items de Orden de Compra',
                'unique_together': {('orden_compra', 'producto')},
            },
        ),
    ]
