# Generated by Django 4.2.24 on 2025-10-05 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devolucion', models.CharField(help_text='Número único de la devolución', max_length=20, unique=True, verbose_name='Número de Devolución')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('cliente_direccion', models.TextField(blank=True, verbose_name='Dirección del Cliente')),
                ('pedido_numero', models.CharField(blank=True, max_length=50, verbose_name='Número de Pedido Original')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha de Entrega Original')),
                ('motivo', models.CharField(choices=[('cliente_rechazo', 'Cliente Rechazó Producto'), ('producto_danado', 'Producto Dañado'), ('producto_vencido', 'Producto Vencido'), ('falta_dinero', 'Cliente Sin Dinero'), ('cambio_pedido', 'Cliente Cambió Pedido'), ('error_despacho', 'Error en Despacho'), ('otro', 'Otro Motivo')], max_length=20, verbose_name='Motivo de Devolución')),
                ('observaciones_repartidor', models.TextField(blank=True, verbose_name='Observaciones del Repartidor')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Recibir'), ('parcial', 'Recibida Parcialmente'), ('completa', 'Recibida Completamente'), ('rechazada', 'Rechazada por Bodega')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción en Bodega')),
                ('observaciones_bodega', models.TextField(blank=True, verbose_name='Observaciones de Bodega')),
                ('total_valor_devuelto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total Devuelto')),
                ('bodeguero_recibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Bodeguero que Recibe')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Repartidor')),
            ],
            options={
                'verbose_name': 'Devolución de Ventas',
                'verbose_name_plural': 'Devoluciones de Ventas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_original', models.PositiveIntegerField(help_text='Cantidad que se pidió originalmente', verbose_name='Cantidad en Pedido Original')),
                ('cantidad_entregada', models.PositiveIntegerField(help_text='Cantidad que se logró entregar al cliente', verbose_name='Cantidad Entregada')),
                ('cantidad_devuelta', models.PositiveIntegerField(help_text='Cantidad que regresa a bodega', verbose_name='Cantidad Devuelta')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, help_text='Cantidad que bodega ha confirmado recibir', verbose_name='Cantidad Recibida en Bodega')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('valor_devuelto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total Devuelto')),
                ('condicion', models.CharField(choices=[('excelente', 'Excelente Estado'), ('buena', 'Buen Estado'), ('regular', 'Estado Regular'), ('mala', 'Mal Estado - No Vendible'), ('dañado', 'Dañado - Pérdida Total')], default='excelente', max_length=20, verbose_name='Condición del Producto')),
                ('ubicacion_bodega', models.CharField(blank=True, help_text='Donde se colocó el producto devuelto', max_length=100, verbose_name='Ubicación en Bodega')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.devolucionventas', verbose_name='Devolución')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de Devolución',
                'verbose_name_plural': 'Items de Devolución',
                'unique_together': {('devolucion', 'producto')},
            },
        ),
    ]
