# Generated by Django 4.2.24 on 2025-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_devolucionventas_devolucionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='link_ubicacion',
            field=models.URLField(blank=True, help_text='URL de Google Maps, Waze u otro servicio de mapas para facilitar la navegación', max_length=500, null=True, verbose_name='Link de Ubicación'),
        ),
    ]
