# Generated by Django 4.2.24 on 2025-10-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_agregar_link_ubicacion_bodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='longitud',
        ),
    ]
