# Generated by Django 4.2.24 on 2025-10-06 14:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0004_eliminar_latitud_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('prioridad', models.CharField(choices=[('critica', 'Crítica - Sin Stock'), ('alta', 'Alta - Stock Muy Bajo'), ('media', 'Media - Stock Bajo'), ('baja', 'Baja - Preventiva')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'En Proceso'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('tipo_analisis', models.CharField(choices=[('stock_minimo', 'Basado en Stock Mínimo'), ('patron_ventas', 'Basado en Patrón de Ventas'), ('tendencia_historica', 'Basado en Tendencia Histórica'), ('estacional', 'Basado en Comportamiento Estacional'), ('predictivo', 'Análisis Predictivo')], max_length=30)),
                ('stock_actual', models.PositiveIntegerField()),
                ('stock_minimo', models.PositiveIntegerField()),
                ('cantidad_sugerida', models.PositiveIntegerField()),
                ('dias_cobertura_actual', models.IntegerField(default=0, help_text='Días que durará el stock actual')),
                ('promedio_ventas_diario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Promedio de unidades vendidas por día', max_digits=10)),
                ('promedio_ventas_semanal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Promedio de unidades vendidas por semana', max_digits=10)),
                ('tendencia_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% de crecimiento/decrecimiento en ventas', max_digits=5)),
                ('precio_sugerido', models.DecimalField(blank=True, decimal_places=2, help_text='Precio sugerido del proveedor', max_digits=12, null=True)),
                ('valor_total_sugerido', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total de la compra sugerida', max_digits=12, null=True)),
                ('fecha_agotamiento_estimada', models.DateField(blank=True, help_text='Fecha estimada de agotamiento del stock', null=True)),
                ('fecha_pedido_sugerida', models.DateField(blank=True, help_text='Fecha sugerida para realizar el pedido', null=True)),
                ('razon_principal', models.CharField(help_text='Razón principal de la recomendación', max_length=200)),
                ('factores_considerados', models.TextField(blank=True, help_text='Factores adicionales considerados en el análisis')),
                ('notas_procesamiento', models.TextField(blank=True, help_text='Notas del procesamiento de la recomendación')),
                ('es_automatica', models.BooleanField(default=True, help_text='Si fue generada automáticamente por el sistema')),
                ('activa', models.BooleanField(default=True, help_text='Si la recomendación está activa')),
                ('procesado_por', models.ForeignKey(blank=True, help_text='Usuario que procesó la recomendación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='inventario.producto')),
                ('proveedor_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Recomendación de Reposición',
                'verbose_name_plural': 'Recomendaciones de Reposición',
                'ordering': ['-fecha_generacion', 'prioridad'],
                'indexes': [models.Index(fields=['producto', 'estado'], name='inventario__product_ebb4bb_idx'), models.Index(fields=['prioridad', 'fecha_generacion'], name='inventario__priorid_d95900_idx'), models.Index(fields=['estado', 'activa'], name='inventario__estado_c20d52_idx')],
            },
        ),
    ]
