# Generated by Django 4.2.24 on 2025-10-06 16:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_recomendacionreposicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Unidad, Caja x6, Caja x12, Paquete x24', max_length=100, verbose_name='Nombre de la presentación')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la presentación', verbose_name='Descripción')),
                ('unidades_por_presentacion', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades que contiene esta presentación', verbose_name='Unidades por presentación')),
                ('costo_presentacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de la presentación')),
                ('precio_minorista_presentacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio minorista de la presentación')),
                ('precio_mayorista_presentacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio mayorista de la presentación')),
                ('es_presentacion_principal', models.BooleanField(default=False, help_text='Marcar si esta es la presentación por defecto', verbose_name='Presentación principal')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de presentación en listas', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Presentación de Producto',
                'verbose_name_plural': 'Presentaciones de Productos',
                'ordering': ['producto__codigo', 'orden', 'nombre'],
                'unique_together': {('producto', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='itemordencomprastock',
            name='presentacion',
            field=models.ForeignKey(blank=True, help_text='Presentación específica del producto (unidad, caja x6, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.presentacionproducto', verbose_name='Presentación'),
        ),
    ]
