# Generated by Django 4.2.24 on 2025-10-06 16:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_agregar_presentaciones_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoproveedor',
            name='stock_proveedor',
        ),
        migrations.CreateModel(
            name='PresentacionProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(blank=True, help_text='Código que usa el proveedor para esta presentación', max_length=50, verbose_name='Código del Proveedor')),
                ('precio_compra_presentacion', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de Compra de la Presentación')),
                ('precio_compra_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Anterior')),
                ('cantidad_minima_pedido', models.PositiveIntegerField(default=1, help_text='Cantidad mínima de esta presentación que se puede pedir', verbose_name='Cantidad Mínima de Pedido')),
                ('tiempo_entrega_dias', models.PositiveIntegerField(default=7, help_text='Tiempo de entrega específico para esta presentación', verbose_name='Días de Entrega')),
                ('descuento_volumen', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Descuento por Volumen')),
                ('cantidad_descuento', models.PositiveIntegerField(default=0, help_text='Cantidad mínima para aplicar el descuento', verbose_name='Cantidad para Descuento')),
                ('disponible', models.BooleanField(default=True, help_text='Si el proveedor actualmente ofrece esta presentación', verbose_name='Disponible')),
                ('es_presentacion_preferida', models.BooleanField(default=False, help_text='Presentación que el proveedor recomienda o prefiere', verbose_name='Presentación Preferida del Proveedor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_ultimo_precio', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Notas específicas para esta presentación del proveedor', verbose_name='Notas')),
                ('presentacion_base', models.ForeignKey(help_text='Presentación base del producto (unidad, caja x6, etc.)', on_delete=django.db.models.deletion.CASCADE, to='inventario.presentacionproducto', verbose_name='Presentación Base')),
                ('producto_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones_disponibles', to='inventario.productoproveedor', verbose_name='Producto-Proveedor')),
            ],
            options={
                'verbose_name': 'Presentación Proveedor-Producto',
                'verbose_name_plural': 'Presentaciones Proveedor-Producto',
                'ordering': ['producto_proveedor__producto__codigo', 'es_presentacion_preferida', 'precio_compra_presentacion'],
                'unique_together': {('producto_proveedor', 'presentacion_base')},
            },
        ),
        migrations.AddField(
            model_name='itemordencomprastock',
            name='presentacion_proveedor',
            field=models.ForeignKey(blank=True, help_text='Presentación específica que ofrece el proveedor para este producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.presentacionproveedorproducto', verbose_name='Presentación del Proveedor'),
        ),
    ]
