# Generated by Django 4.2.24 on 2025-10-07 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0007_presentaciones_dinamicas_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('agotado', 'Producto Agotado'), ('cerca_minimo', 'Cerca del Mínimo')], max_length=20, verbose_name='Tipo de Alerta')),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('advertencia', 'Advertencia'), ('critico', 'Crítico')], default='advertencia', max_length=15, verbose_name='Nivel de Alerta')),
                ('mensaje', models.TextField(verbose_name='Mensaje de la Alerta')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock Actual al momento de la alerta')),
                ('stock_minimo', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('activa', models.BooleanField(default=True, verbose_name='Alerta Activa')),
                ('vista', models.BooleanField(default=False, verbose_name='Vista por usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_resuelto', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_stock', to='inventario.producto', verbose_name='Producto')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-fecha_creacion', 'nivel', 'producto__codigo'],
                'unique_together': {('producto', 'tipo_alerta')},
            },
        ),
    ]
