# Generated by Django 4.2.24 on 2025-10-05 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('demanda', 'Análisis de Demanda'), ('clientes', 'Análisis de Clientes'), ('proveedores', 'Análisis de Proveedores'), ('inventario', 'Optimización de Inventario'), ('mrp', 'Planificación MRP')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('datos_reporte', models.JSONField()),
                ('recomendaciones', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('productos_analizados', models.IntegerField(default=0)),
                ('clientes_analizados', models.IntegerField(default=0)),
                ('precision_promedio', models.FloatField(default=0.0)),
                ('usuario_generacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Análisis',
                'verbose_name_plural': 'Reportes de Análisis',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='PrediccionDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda_7dias', models.IntegerField(default=0)),
                ('demanda_15dias', models.IntegerField(default=0)),
                ('demanda_30dias', models.IntegerField(default=0)),
                ('demanda_60dias', models.IntegerField(default=0)),
                ('demanda_90dias', models.IntegerField(default=0)),
                ('estacionalidad_factor', models.FloatField(default=1.0)),
                ('tendencia_crecimiento', models.FloatField(default=0.0)),
                ('precision_modelo', models.FloatField(default=0.0)),
                ('error_promedio', models.FloatField(default=0.0)),
                ('cantidad_recomendada_compra', models.IntegerField(default=0)),
                ('punto_reorden_sugerido', models.IntegerField(default=0)),
                ('stock_seguridad_sugerido', models.IntegerField(default=0)),
                ('riesgo_desabastecimiento', models.CharField(choices=[('bajo', 'Riesgo Bajo'), ('medio', 'Riesgo Medio'), ('alto', 'Riesgo Alto'), ('critico', 'Riesgo Crítico')], default='medio', max_length=10)),
                ('fecha_prediccion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Predicción de Demanda',
                'verbose_name_plural': 'Predicciones de Demanda',
                'get_latest_by': 'fecha_prediccion',
            },
        ),
        migrations.CreateModel(
            name='ParametrosMRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizonte_planificacion_dias', models.IntegerField(default=90)),
                ('factor_seguridad_stock', models.FloatField(default=1.2)),
                ('ventana_historica_dias', models.IntegerField(default=365)),
                ('peso_tendencia_reciente', models.FloatField(default=0.7)),
                ('umbral_stock_critico', models.FloatField(default=0.1)),
                ('umbral_precision_minima', models.FloatField(default=0.7)),
                ('es_configuracion_activa', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parámetros MRP',
                'verbose_name_plural': 'Parámetros MRP',
            },
        ),
        migrations.CreateModel(
            name='AnalisisProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenes_totales', models.IntegerField(default=0)),
                ('ordenes_a_tiempo', models.IntegerField(default=0)),
                ('ordenes_completas', models.IntegerField(default=0)),
                ('puntualidad_promedio', models.FloatField(default=0.0)),
                ('completitud_promedio', models.FloatField(default=0.0)),
                ('competitividad_precios', models.FloatField(default=0.0)),
                ('estabilidad_precios', models.FloatField(default=0.0)),
                ('capacidad_estimada', models.IntegerField(default=0)),
                ('tiempo_entrega_promedio', models.FloatField(default=0.0)),
                ('clasificacion', models.CharField(choices=[('estrategico', 'Proveedor Estratégico'), ('preferido', 'Proveedor Preferido'), ('aprobado', 'Proveedor Aprobado'), ('critico', 'Proveedor en Revisión')], default='aprobado', max_length=20)),
                ('nivel_riesgo', models.FloatField(default=0.5)),
                ('fecha_analisis', models.DateTimeField(auto_now=True)),
                ('proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Análisis de Proveedor',
                'verbose_name_plural': 'Análisis de Proveedores',
            },
        ),
        migrations.CreateModel(
            name='EventoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('ajuste', 'Ajuste de Inventario'), ('devolucion', 'Devolución'), ('merma', 'Merma/Pérdida')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_resultante', models.IntegerField()),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_inventario', to='inventario.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Inventario',
                'verbose_name_plural': 'Eventos de Inventario',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['producto', 'fecha_evento'], name='analytics_e_product_2d83f0_idx'), models.Index(fields=['cliente', 'fecha_evento'], name='analytics_e_cliente_befb0e_idx'), models.Index(fields=['tipo_evento', 'fecha_evento'], name='analytics_e_tipo_ev_181d69_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalisisVentasCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pedidos', models.IntegerField(default=0)),
                ('cantidad_total_comprada', models.IntegerField(default=0)),
                ('valor_total_comprado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frecuencia_compra_dias', models.FloatField(default=0)),
                ('mes_mayor_actividad', models.IntegerField(default=1)),
                ('dia_semana_preferido', models.IntegerField(default=1)),
                ('precio_promedio_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sensibilidad_precio', models.FloatField(default=0)),
                ('demanda_predicha_30dias', models.IntegerField(default=0)),
                ('demanda_predicha_60dias', models.IntegerField(default=0)),
                ('demanda_predicha_90dias', models.IntegerField(default=0)),
                ('categoria_cliente', models.CharField(choices=[('premium', 'Cliente Premium'), ('frecuente', 'Cliente Frecuente'), ('ocasional', 'Cliente Ocasional'), ('nuevo', 'Cliente Nuevo'), ('inactivo', 'Cliente Inactivo')], default='nuevo', max_length=20)),
                ('fecha_analisis', models.DateTimeField(auto_now=True)),
                ('confiabilidad_prediccion', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ventas', to='ventas.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_por_cliente', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Análisis de Ventas por Cliente',
                'verbose_name_plural': 'Análisis de Ventas por Cliente',
                'unique_together': {('cliente', 'producto')},
            },
        ),
    ]
