# Generated by Django 4.2.24 on 2025-10-05 12:40

from django.db import migrations, models


def generate_numero_entrega(apps, schema_editor):
    """Generar números únicos para entregas existentes"""
    Entrega = apps.get_model('ventas', 'Entrega')
    for i, entrega in enumerate(Entrega.objects.all(), 1):
        entrega.numero = f"ENT{i:05d}"
        entrega.save()


def reverse_generate_numero_entrega(apps, schema_editor):
    """Revertir - no hacer nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        # Agregar campo numero con valor temporal
        migrations.AddField(
            model_name='entrega',
            name='numero',
            field=models.CharField(default='TEMP', max_length=20),
        ),
        # Generar números únicos para entregas existentes
        migrations.RunPython(generate_numero_entrega, reverse_generate_numero_entrega),
        # Hacer el campo único
        migrations.AlterField(
            model_name='entrega',
            name='numero',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
