# Generated by Django 4.2.24 on 2025-10-05 13:37

from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


def limpiar_items_existentes(apps, schema_editor):
    """Eliminar items existentes ya que no tienen producto asociado"""
    ItemPedido = apps.get_model('ventas', 'ItemPedido')
    count = ItemPedido.objects.count()
    ItemPedido.objects.all().delete()
    print(f"Eliminados {count} items de pedido existentes (sin producto)")


def reversa_limpiar_items(apps, schema_editor):
    """No hacer nada en reversa"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_add_numero_entrega'),
        ('inventario', '0001_initial'),  # Usar la migración inicial de inventario
    ]

    operations = [
        # Primero limpiar datos existentes
        migrations.RunPython(limpiar_items_existentes, reversa_limpiar_items),
        
        # Renombrar precio a precio_unitario
        migrations.RenameField(
            model_name='itempedido',
            old_name='precio',
            new_name='precio_unitario',
        ),
        
        # Cambiar cantidad de PositiveIntegerField a DecimalField
        migrations.AlterField(
            model_name='itempedido',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        
        # Agregar campo producto
        migrations.AddField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        
        # Agregar related_name al pedido
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.pedido'),
        ),
    ]
