# Generated by Django 4.2.24 on 2025-10-05 13:53

from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_auto_20251005_0837'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        # Renombrar precio a precio_unitario
        migrations.RenameField(
            model_name='itemcotizacion',
            old_name='precio',
            new_name='precio_unitario',
        ),
        
        # Cambiar cantidad de PositiveIntegerField a DecimalField
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        
        # Agregar campo producto
        migrations.AddField(
            model_name='itemcotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        
        # Agregar related_name a la cotización
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.cotizacion'),
        ),
    ]
