# Generated by Django 4.2.24 on 2025-10-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_auto_20251005_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_credito',
            field=models.IntegerField(default=0, help_text='Días de crédito permitidos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Límite de crédito en pesos', max_digits=12),
        ),
    ]
