# Generated by Django 4.2.24 on 2025-10-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0014_cliente_dias_credito_cliente_limite_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
