# Generated by Django 4.2.24 on 2025-10-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_pedido_asignado_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('en_proceso', 'En Proceso')], default='borrador', max_length=20),
        ),
    ]
