# Generated by Django 4.2.24 on 2025-10-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRechazado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_rechazada', models.DecimalField(decimal_places=2, help_text='Cantidad del item que fue rechazada', max_digits=10)),
                ('motivo', models.CharField(choices=[('defectuoso', 'Producto defectuoso'), ('incorrecto', 'Producto incorrecto'), ('no_solicitado', 'No fue solicitado'), ('cambio_opinion', 'Cliente cambió de opinión'), ('precio', 'Problema con el precio'), ('otro', 'Otro motivo')], default='otro', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el rechazo')),
                ('fecha_rechazo', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_rechazados', to='ventas.entrega')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.itempedido')),
            ],
            options={
                'verbose_name': 'Item Rechazado',
                'verbose_name_plural': 'Items Rechazados',
                'unique_together': {('entrega', 'item_pedido')},
            },
        ),
    ]
