# Generated by Django 4.2.24 on 2025-10-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_itemrechazado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.factura'),
        ),
    ]
