# Generated by Django 5.2.7 on 2025-10-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventario', '0008_alertastock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bodega',
            field=models.ForeignKey(blank=True, help_text='Bodega a la que pertenece el usuario (solo para bodegueros)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.bodega', verbose_name='Bodega asignada'),
        ),
    ]
