# Generated by Django 4.2.24 on 2025-10-05 12:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Oportunidad')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Estimado')),
                ('probabilidad', models.PositiveIntegerField(default=50, help_text='Probabilidad de cierre (0-100%)', verbose_name='Probabilidad (%)')),
                ('estado', models.CharField(choices=[('prospecto', 'Prospecto'), ('calificado', 'Calificado'), ('propuesta', 'Propuesta Enviada'), ('negociacion', 'En Negociación'), ('cerrado_ganado', 'Cerrado Ganado'), ('cerrado_perdido', 'Cerrado Perdido')], default='prospecto', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('fuente', models.CharField(choices=[('web', 'Sitio Web'), ('referencia', 'Referencia'), ('llamada_fria', 'Llamada Fría'), ('redes_sociales', 'Redes Sociales'), ('evento', 'Evento/Feria'), ('email', 'Email Marketing'), ('publicidad', 'Publicidad'), ('otro', 'Otro')], default='web', max_length=20, verbose_name='Fuente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Cierre Estimada')),
                ('fecha_cierre_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cierre Real')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('productos_interes', models.TextField(blank=True, help_text='Productos o servicios de interés del cliente', verbose_name='Productos de Interés')),
                ('competencia', models.TextField(blank=True, help_text='Información sobre competidores', verbose_name='Competencia')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='ventas.cliente', verbose_name='Cliente')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotaOportunidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField(verbose_name='Contenido de la Nota')),
                ('es_publica', models.BooleanField(default=True, help_text='Si está marcado, todos los usuarios pueden ver esta nota', verbose_name='Visible para todo el equipo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='crm.oportunidad', verbose_name='Oportunidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada Telefónica'), ('email', 'Email'), ('reunion', 'Reunión'), ('presentacion', 'Presentación'), ('seguimiento', 'Seguimiento'), ('propuesta', 'Envío de Propuesta'), ('visita', 'Visita Cliente'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Actividad')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_actividad', models.DateTimeField(verbose_name='Fecha/Hora de la Actividad')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('resultado', models.TextField(blank=True, help_text='Resultado o conclusiones de la actividad', verbose_name='Resultado')),
                ('proxima_accion', models.TextField(blank=True, help_text='Próximos pasos a seguir', verbose_name='Próxima Acción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='crm.oportunidad', verbose_name='Oportunidad')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha_actividad'],
            },
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='crm_oportun_estado_a6f805_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['vendedor', 'estado'], name='crm_oportun_vendedo_3835d6_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['cliente'], name='crm_oportun_cliente_c5ca3c_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['fecha_actividad', 'responsable'], name='crm_activid_fecha_a_934272_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['oportunidad', 'completada'], name='crm_activid_oportun_c3f0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['tipo', 'fecha_actividad'], name='crm_activid_tipo_0d6fec_idx'),
        ),
    ]
