# Generated by Django 4.2.24 on 2025-10-07 22:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0018_alter_itemfactura_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_visita', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimensual', 'Bimensual'), ('trimestral', 'Trimestral')], default='mensual', max_length=20, verbose_name='Frecuencia de Visita')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('activa', models.BooleanField(default=True, verbose_name='Asignación Activa')),
                ('ultima_visita', models.DateTimeField(blank=True, null=True, verbose_name='Última Visita')),
                ('proxima_visita', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Visita Programada')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre la asignación o instrucciones especiales', verbose_name='Notas de Asignación')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_vendedor', to='ventas.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Asignación de Cliente',
                'verbose_name_plural': 'Asignaciones de Clientes',
                'ordering': ['vendedor__username', 'cliente__nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionRutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_default', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimensual', 'Bimensual'), ('trimestral', 'Trimestral')], default='mensual', max_length=20, verbose_name='Frecuencia por Defecto')),
                ('dias_alerta_vencimiento', models.PositiveIntegerField(default=3, help_text='Días antes del vencimiento para mostrar alertas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Días de Alerta')),
                ('max_clientes_por_vendedor', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Máximo Clientes por Vendedor')),
                ('auto_reprogramar', models.BooleanField(default=True, help_text='Programar automáticamente la siguiente visita al completar una', verbose_name='Auto-reprogramar Visitas')),
            ],
            options={
                'verbose_name': 'Configuración de Rutas',
                'verbose_name_plural': 'Configuración de Rutas',
            },
        ),
        migrations.CreateModel(
            name='VisitaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha Programada')),
                ('fecha_realizada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Realizada')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20, verbose_name='Estado')),
                ('resultado', models.CharField(blank=True, choices=[('exitosa', 'Exitosa'), ('sin_contacto', 'Sin Contacto'), ('no_interesado', 'No Interesado'), ('pedido_realizado', 'Pedido Realizado'), ('seguimiento', 'Requiere Seguimiento')], max_length=20, verbose_name='Resultado de la Visita')),
                ('observaciones', models.TextField(blank=True, help_text='Detalles de la visita, comentarios del cliente, etc.', verbose_name='Observaciones')),
                ('productos_mostrados', models.TextField(blank=True, help_text='Lista de productos presentados al cliente', verbose_name='Productos Mostrados')),
                ('requiere_seguimiento', models.BooleanField(default=False, verbose_name='Requiere Seguimiento')),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='rutas.asignacioncliente', verbose_name='Asignación')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('pedido_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visita_origen', to='ventas.pedido', verbose_name='Pedido Generado')),
            ],
            options={
                'verbose_name': 'Visita a Cliente',
                'verbose_name_plural': 'Visitas a Clientes',
                'ordering': ['-fecha_programada'],
                'indexes': [models.Index(fields=['estado', 'fecha_programada'], name='rutas_visit_estado_03c589_idx'), models.Index(fields=['asignacion', 'fecha_realizada'], name='rutas_visit_asignac_ad408f_idx'), models.Index(fields=['resultado'], name='rutas_visit_resulta_25f0e4_idx'), models.Index(fields=['requiere_seguimiento'], name='rutas_visit_requier_b85dbb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asignacioncliente',
            index=models.Index(fields=['vendedor', 'activa'], name='rutas_asign_vendedo_3a2a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacioncliente',
            index=models.Index(fields=['proxima_visita'], name='rutas_asign_proxima_455d46_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacioncliente',
            index=models.Index(fields=['frecuencia_visita'], name='rutas_asign_frecuen_18081c_idx'),
        ),
    ]
